### ISSUE TITLE
[FEATURE] Result by winning player (in addition to winning colour)

### ISSUE THREAD

**Issue by Manit100** [agadmator-library/agadmator-library.github.io#11]
**Is your feature request related to a problem? Please describe.**
Quickest way to understand is by trying to list:
_What games did Magnus Carlsen lose?_

Currently, if I try...
[any side][Magnus Carlsen]
...I have nothing to enter in **Result** (white won / black won / draw / NA), because I do not know whether Carlsen had white or black pieces. I don't want to leave the **Result** field as is, because Carlsen has won lots of games, and in this case, I would not be interested in those games.

So my current workaround is to use 2 separate queries:
Browser tab 1: [white pieces][Magnus Carlsen][black won]
Browser tab 2: [black pieces][Magnus Carlsen][white won]

This is totally fine, but it would be better if...

**Describe the solution you'd like**
Under **Result**, there should be two filters:
1. Choose the winning **side** based on colour (white won / black won / draw / NA)
and/or
2. Choose the winning **player** by name

Filter 1 already exists and works great. 
Filter 2 does not exist at the moment and could be added as a drop-down. The drop-down would ideally be a sub-list with only _valid_ names. In other words, once someone starts their query with:
[any side][Magnus Carlsen]
...then in the **winning player** drop-down list, they should be able to search for and select _Daniil Dubov_ (Dubov has beaten Carlsen at least once), _Viswanathan Anand_ as an option (same logic), but not _Paul Charles Morphy_ (who lived from 1837 to 1884 and sadly, could never beat Carlsen).

However, please note that a _filtered_ sub-list is just a nice-to-have. If it seems tedious to implement, an _unfiltered_ sub-list (of all player names in the db) is still a useful enhancement. Yes, if someone tries [any side][Magnus Carlsen] with winning player [Paul Charles Morphy], they would get no results, but that seems okay to me, personally.

**Additional context**
All this is limited to Agad videos, of course :)

**Comment by agadmator-library** [comment]
Right now filters of same type work with OR condition (so adding White:Anand and White:Carlsen will result in games where either one played with white pieces). Filters with different type are connected by AND condition (so White:Carlsen and Black:Anand will result in games between those two players where Carlsen had white pieces).

I think with little refactor I can change player filter to hold 3 params (side, player, won/lost/draw) instead of current 2 (side/player). This would result in additional drop down next to player name.

As there are already more and more filters it is possible that I will add this extra dropdown only on desktop version

**Comment by agadmator-library** [comment]
Filter added

**Comment by agadmator-library** [comment]
And one afterthought 
Do remember that a lot of games do not have results assigned. I'm extracting results using 3rd party services (chess.com and chesstempo.com) instead of trying to parse them from description.
Of 3060 videos only 2400 have results.
By applying filters you are limiting number of videos you'll see.

**Comment by Manit100** [comment]
You, sir, are an absolute legend. 53 minutes to implement a feature request and close the ticket — I can think of entire development _teams_ that I wish demonstrated that sort of speed and work-ethic.

On the incomplete result data: Noted. I was just thinking about the long-term rather than the immediate uses. Thank you once again.
